# Data Cleaning in Panadas

Check for any duplicate if any remove them

Standerized data and fix errors

Remove unwanted columns

In [582]:
import pandas as pd

In [583]:
## import dataset 

df=pd.read_excel("dataset\ccl.xlsx")

In [584]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [585]:
 type(df)

pandas.core.frame.DataFrame

In [586]:
fd=df.duplicated()

In [587]:
df.iloc[20]

CustomerID                                  1020
First_Name                                Anakin
Last_Name                              Skywalker
Phone_Number                        876|678|3469
Address              910 Tatooine Road, Tatooine
Paying Customer                              Yes
Do_Not_Contact                                 N
Not_Useful_Column                           True
Name: 20, dtype: object

In [588]:
df.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [589]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [590]:
df.drop_duplicates(inplace=True)

In [591]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [592]:
df.duplicated().sum()

np.int64(0)

In [593]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [594]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [595]:
df['Last_Name']=df['Last_Name'].str.strip("123._/") #reg expression

In [596]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [597]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [598]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

# steps to make all numbers in the phone number column to be of same length and format
# step1-replace all the unwanted character to emty string( "")

In [599]:
#python string
name="mike-tyson"
type(name)
name.replace("-","")

'miketyson'

In [600]:
#python string
name="mike-tyson"
name.replace("-","")

#mike/tyson
name[0:4]+"/"+name[4:9] # "mike/tyson"

'mike/-tyso'

# abc-def-ghij

In [601]:
l1=lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]

# apply()=> Apply is a pandas function which will appiled specified functionslity to each value of series

In [602]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x : str(x))

In [603]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              nan
7     876|678|3469
8              N/a
9     123-545-5421
10             nan
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [604]:
df['Phone_Number'].str.replace("[^0-9]","",regex=True)

0     1235455421
1     1236439775
2     7066950392
3     1235432345
4     8766783469
5     3047622467
6
7     8766783469
8
9     1235455421
10
11    7066950392
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17    7066950392
18
19    8766783469
Name: Phone_Number, dtype: object

In [605]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              nan
7     876|678|3469
8              N/a
9     123-545-5421
10             nan
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [606]:
l1=lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]

In [607]:
df['Phone_Number']=df['Phone_Number'].apply(l1)

In [608]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-/64-3/97,93 West Main Street,No,Yes,False
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-|67-8|34,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-|67-8|34,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-|67-8|34,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-/64-3/97,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-|67-8|34,"910 Tatooine Road, Tatooine",Yes,N,True

In [609]:
df['Address']

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: object

In [610]:
# adress
df['Address'].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [611]:
# spliting address into 3 sep cols
df[['Street_Address','City','Pin_Code']]=df['Address'].str.split(',',expand=True)

In [612]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-/64-3/97,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-|67-8|34,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-|67-8|34,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a--,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-|67-8|34,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-/64-3/97,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a--,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-|67-8|34,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [613]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')

In [614]:
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')

In [615]:
df['Paying Customer']

0       Y
1       N
2       N
3       Y
4       Y
5       Y
6       N
7       N
8       Y
9       Y
10      Y
11      Y
12      Y
13      Y
14      N
15      N
16      Y
17      Y
18    N/a
19      Y
Name: Paying Customer, dtype: object

In [616]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')

In [617]:
df['Do_Not_Contact']

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [618]:
# remove columns
df.drop(columns=['Not_Useful_Column','Address'],inplace=True)

In [619]:
fullname="virat kholi"
fullname.split(',')

['virat kholi']

In [620]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123--54-5-54,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-/64-3/97,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123--54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-|67-8|34,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304--76-2-24,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-|67-8|34,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a--,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123--54-5-54,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan--,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123--54-3-23,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-|67-8|34,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304--76-2-24,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123--54-5-54,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-/64-3/97,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a--,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-|67-8|34,Y,N,910 Tatooine Road,Tatooine,None

## Dealing with null values

In [621]:
df.replace('N/a','',inplace=True)
df.replace('NAn','',inplace=True)

In [629]:
df.replace('--','',inplace=True)

In [630]:
df.fillna('',inplace=True)

In [634]:
for i in df.index:
        if df.loc[i,'Do_Not_Contact'] == "Y" or df.loc[i,'Phone_Number'] =="":
                df.drop(i,inplace=True)

In [635]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123--54-5-54,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-0392,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-|67-8|34,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,nan--,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-|67-8|34,N,N,98 Clue Drive,,
8,1009,Gandalf,,N/a--,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123--54-5-54,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123--54-3-23,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-|67-8|34,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304--76-2-24,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-/64-3/97,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-|67-8|34,Y,N,910 Tatooine Road,Tatooine,

In [636]:
for i in df.index:
        if df.loc[i,'Phone_Number'] == "":
                df.drop(i,inplace=True)

In [637]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123--54-5-54,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,706-695-0392,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-|67-8|34,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,nan--,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-|67-8|34,N,N,98 Clue Drive,,
8,1009,Gandalf,,N/a--,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123--54-5-54,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123--54-3-23,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-|67-8|34,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304--76-2-24,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123--54-5-54,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-/64-3/97,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-|67-8|34,Y,N,910 Tatooine Road,Tatooine,